### ISSUE TITLE
Update to make it usable on mobile.

### ISSUE THREAD

**Issue by Shivam-Amin** [Shivam-Amin/Order-Summary-Component#1]
**Hello everyone!!** This repo only contains only **_HTML & CSS._**
- This is my first repository on github platform.

- I am learning web development via creating some real world projects. :smile:

- If you want to contribute to this repo please let me know in this discussion below. :writing_hand:

:arrow_right: Please do not make a pull request without any discussion, it may not be accepted.

**Comment by tarek-mo** [comment]
Hello, I have some decent experience with HTML/CSS but still beginner with contributing to others repos, so maybe we can help each other?

**Comment by Shivam-Amin** [comment]
Hi @tarek-mo, I'm very pleased for your interest and passion to contributing to opensource.
Ok then let's get started. If you need any help let me know. You can also tag me on twitter @ShivamAmin1126 👍

**Comment by salehghulamqasim** [comment]
Hi @Shivam-Amin if there is place for one more contributor i would love to join since i am also beginner and been learning html and css and doing some basic projects by my own. i would like to take it to another level by creating realistic projects with you guys.

**Comment by Shivam-Amin** [comment]
@salehghulamqasim what can you add to this repo. Let me know if the idea is good then we can work on it.

**Comment by salehghulamqasim** [comment]
**hi sorry for such late reply** . i was thinking about putting some dark and light mode option.Maybe put a manual toggle to allow user choose what he wants or maybe keep it according to the user's device setting. For now i would like to do just that bcuz i am new in pulling and pushing git, this is my first time so hopefully if i knew how to do that i would be honored to contribute further more

**Comment by Shivam-Amin** [comment]
Ok Nice idea. 
- Can you put a switch on the right upper corner so that user can switch between light and dark mode.
Reply yes so that I can create an issue.
- And If you need any help related git no worries you can ask or you can watch this video : 
https://www.youtube.com/watch?v=apGV9Kg7ics&t=3149s&ab_channel=KunalKushwaha .
